site_name: ML & AI Knowledge Hub

nav:
  - Home: index.md
  - Activation Functions: DeepLearning/activation_functions.md
  - Libraries: 
    - All: Libraries/libraries.md
    - Torch: Libraries/torch.md
    - Keras: Libraries/keras.md
  - Methods: Libraries/methods.md
  - Optimizers: DeepLearning/optimizers.md
  - Layers: DeepLearning/layers.md
  - CNN: DeepLearning/CNN.md
  - GenAI:
    - Overview: GenAI/GenAI.md
    - Tokenization: GenAI/tokenization.md
    - NGrams: GenAI/ngrams.md
    - Word_Embeddings: GenAI/embeddings.md
    - Seq2Seq_RNNs: GenAI/seq2seq_rnn.md
    - Transformers: GenAI/transformers.md
    - Metrics: GenAI/metrics.md
    - Tuning: GenAI/tuning.md
  - LLM:
    - Overview: LLM/LLM.md
    - BERT: LLM/BERT.md
    - NER: LLM/NER.md
  - Extra:
    - 3B1B: 3Blue1Brown.md

theme:
  name: material

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
