site_name: ML & AI Knowledge Hub

nav:
  - Home: index.md
  - Libraries: 
    - All: Libraries/libraries.md
    - Torch: Libraries/torch.md
    - Keras: Libraries/keras.md
  - Methods: Libraries/methods.md
  - Optimizers: DeepLearning/optimizers.md
  - CNN: DeepLearning/CNN.md
  - 3B1B: 3Blue1Brown.md
  - LLM:
    - Overview: LLM/LLM.md
    - BERT: LLM/BERT.md
  - AF: DeepLearning/activation_functions.md
  - GenAI: GenAI.md
  - Layers: DeepLearning/layers.md

theme:
  name: material

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
