site_name: ML & AI Knowledge Hub

nav:
  - Home: index.md
  - Libraries: 
    - All: libraries.md
    - Torch: torch.md
  - Methods: methods.md
  - Optimizers: optimizers.md
  - CNN: CNN.md
  - 3B1B: 3Blue1Brown.md
  - LLM: LLM.md

theme:
  name: material

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
