site_name: ML & AI Knowledge Hub

nav:
  - Home: index.md
  - Activation Functions: DeepLearning/activation_functions.md
  - Libraries: 
    - All: Libraries/libraries.md
    - Torch: Libraries/torch.md
    - Keras: Libraries/keras.md
  - Methods: Libraries/methods.md
  - Optimizers: DeepLearning/optimizers.md
  - Layers: DeepLearning/layers.md
  - CNN: DeepLearning/CNN.md
  - GenAI:
    - Overview: GenAI/GenAI.md
    - Tokenization: GenAI/tokenization.md
    - NGrams: GenAI/ngrams.md
    - Word_Embeddings: GenAI/embeddings.md
    - Seq2Seq_RNNs: GenAI/seq2seq_rnn.md
    - Transformers: GenAI/transformers.md
    - Metrics: GenAI/metrics.md
    - Tuning: GenAI/tuning.md
  - LLM:
    - Overview: LLM/LLM.md
    - BERT: LLM/BERT.md
    - XLNet: LLM/XLNet.md
    - NER: LLM/NER.md
    - Tuning: LLM/tuning.md
  - AI Agents:
    - Overview: Agents/overview.md
    - RAG: Agents/RAG.md
    - LangChain: Agents/langchain.md
  - Extra:
    - 3B1B: 3Blue1Brown.md
  # --- Networking Fundamentals ---
  # - Networking:
  #   - Overview: Networking/overview.md
    # - OSI_Model: Networking/osi_model.md
    # - Routing: Networking/routing.md
    # - Switching: Networking/switching.md
    # - Protocols:
    #   - TCP_IP: Networking/Protocols/tcp_ip.md
    #   - UDP: Networking/Protocols/udp.md
    #   - HTTP_REST: Networking/Protocols/http_rest.md
    #   - DNS: Networking/Protocols/dns.md
    # - Virtualization: Networking/virtualization.md
    # - Containers: Networking/containers.md
  # --- AI & ML in Networking ---
  - AI in Networking:
    - Overview: AI_Networking/overview.md
    # - Network_Traffic_Prediction: AI_Networking/traffic_prediction.md
    # - 5G_Networks: AI_Networking/5g_networks.md
    # - SDN_ML_Optimization: AI_Networking/sdn_optimization.md
    # - Network_Security_AI: AI_Networking/security_ai.md
    # - Fault_Detection: AI_Networking/fault_detection.md
    # - Edge_Computing: AI_Networking/edge_computing.md
theme:
  name: material

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
