name: Auto Commit Non-Hidden Files

on:
  schedule:
    - cron: '0 17 * * *'  # Schedule at 5 PM UTC daily

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Update Non-Hidden Files
      run: |
        # Add a timestamp to a file to ensure there is always a change
        echo "Last updated on: $(date)" > update.txt

        # Stage all non-hidden files in the repository
        git add *

        # Use dynamic commit messages
        messages=("Minor updates" "Latest changes" "Improvements made" "Adjustments and tweaks" "Updated project files" "General updates")
        random_index=$((RANDOM % ${#messages[@]}))
        commit_message="${messages[$random_index]}"
        # Commit the changes
        git commit -m "$commit_message" || echo "No changes to commit"
   
      
    - uses: stefanzweifel/git-auto-commit-action@v5
